language: node_js
node_js:
  - "0.10"
before_script:
  - npm install -g hoodie-cli
  - npm install -g casperjs
  - npm install -g grunt-cli
services:
  - couchdb
notifications:
  irc:
    channels:
      - "irc.freenode.net#hoodie"
    use_notice: false
    skip_join: true

sudo: false
cache:
  directories:
  - node_modules
